openapi: 3.2.0
info:
  title: Fenergo Nebula ConfigBaseline Query Baseline API
  description: '**ConfigBaseline Query API**:


    ConfigBaseline Query API is part of FenX eco-system to query configuration baseline.'
  version: 1.9.3
servers:
- url: /configbaselinequery
security:
- Bearer: []
tags:
- name: Baseline
paths:
  /api/baseline/latest:
    get:
      tags:
      - Baseline
      summary: Get baselines
      description: 'Returns a list of the latest baselines for a given tenant


        Required permissions:

        Following permissions are required: ConfigBaselineAccess'
      operationId: GetLatest
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: Success. The list of Configuration Baselines is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaselineDtoIEnumerableServiceResponse'
              example:
                data:
                - id: 4a7135da-dae0-4b7b-89e4-b62cb889f534
                  configType: Lookup
                  effectiveFrom: '2026-09-09T21:47:52.7930452+00:00'
                  activeVersions:
                    585f5742-11e9-4e6a-b248-8923617a7e01: 1
                    87177e7e-2a5a-4af8-a018-aa0e50c11795: 4
                    22606499-9ee9-49ee-9832-31c1514e04ca: 20
                    8d345797-c425-47f5-acb4-b8cc6312a72a: 8
                    32a91d26-39a7-4982-8f7b-43e2071054a2: 75
                    c50587e5-7baa-4786-8ad0-4dbda72ca01d: 32
                - id: 267731da-24b4-4a43-a717-3e5a06540193
                  configType: LookupLink
                  effectiveFrom: '2026-09-09T21:47:52.8044412+00:00'
                  activeVersions:
                    17730e55-a0de-46bd-96d2-b3ea508a3d5f: 21
                    291c9f8a-5c05-46d5-b257-ff39f25ec15f: 8
                    b2d5975d-b164-4533-9f3c-54e0639bb89a: 16
                    4cb67e7f-153e-440b-9946-5c8036d71c41: 8
                messages: null
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
  /api/baseline/reference/{referenceId}:
    get:
      tags:
      - Baseline
      summary: Get baselines
      description: 'Returns a list of the baselines within a given baselines reference.


        Required permissions:

        Following permissions are required: ConfigBaselineAccess'
      operationId: GetByReference
      parameters:
      - name: referenceId
        in: path
        description: BaselinesReference identifier.
        required: true
        schema:
          type: string
          format: uuid
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: Success. The list of Configuration Baselines is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaselineDtoIEnumerableServiceResponse'
              example:
                data:
                - id: 4a7135da-dae0-4b7b-89e4-b62cb889f534
                  configType: Lookup
                  effectiveFrom: '2026-09-09T21:47:52.8659759+00:00'
                  activeVersions:
                    585f5742-11e9-4e6a-b248-8923617a7e01: 1
                    87177e7e-2a5a-4af8-a018-aa0e50c11795: 4
                    22606499-9ee9-49ee-9832-31c1514e04ca: 20
                    8d345797-c425-47f5-acb4-b8cc6312a72a: 8
                    32a91d26-39a7-4982-8f7b-43e2071054a2: 75
                    c50587e5-7baa-4786-8ad0-4dbda72ca01d: 32
                - id: 267731da-24b4-4a43-a717-3e5a06540193
                  configType: LookupLink
                  effectiveFrom: '2026-09-09T21:47:52.8660133+00:00'
                  activeVersions:
                    17730e55-a0de-46bd-96d2-b3ea508a3d5f: 21
                    291c9f8a-5c05-46d5-b257-ff39f25ec15f: 8
                    b2d5975d-b164-4533-9f3c-54e0639bb89a: 16
                    4cb67e7f-153e-440b-9946-5c8036d71c41: 8
                messages: null
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: BaselinesReference doesn't exist.
                  type: Error
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
  /api/baseline/reference/journey/{journeyId}:
    get:
      tags:
      - Baseline
      summary: Get baselines
      description: 'Returns a list of the baselines linked to the journey.


        Required permissions:

        Following permissions are required: JourneyAccess'
      operationId: GetByJourney
      parameters:
      - name: journeyId
        in: path
        description: Journey identifier.
        required: true
        schema:
          type: string
          format: uuid
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: Success. The list of Configuration Baselines is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaselineDtoIEnumerableServiceResponse'
              example:
                data:
                - id: 4a7135da-dae0-4b7b-89e4-b62cb889f534
                  configType: Lookup
                  effectiveFrom: '2026-09-09T21:47:52.9240937+00:00'
                  activeVersions:
                    585f5742-11e9-4e6a-b248-8923617a7e01: 1
                    87177e7e-2a5a-4af8-a018-aa0e50c11795: 4
                    22606499-9ee9-49ee-9832-31c1514e04ca: 20
                    8d345797-c425-47f5-acb4-b8cc6312a72a: 8
                    32a91d26-39a7-4982-8f7b-43e2071054a2: 75
                    c50587e5-7baa-4786-8ad0-4dbda72ca01d: 32
                - id: 267731da-24b4-4a43-a717-3e5a06540193
                  configType: LookupLink
                  effectiveFrom: '2026-09-09T21:47:52.9241282+00:00'
                  activeVersions:
                    17730e55-a0de-46bd-96d2-b3ea508a3d5f: 21
                    291c9f8a-5c05-46d5-b257-ff39f25ec15f: 8
                    b2d5975d-b164-4533-9f3c-54e0639bb89a: 16
                    4cb67e7f-153e-440b-9946-5c8036d71c41: 8
                messages: null
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: BaselinesReference doesn't exist.
                  type: Error
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    ServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    BaselineDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        configType:
          type:
          - string
          - 'null'
        effectiveFrom:
          type: string
          format: date-time
        activeVersions:
          type:
          - object
          - 'null'
          additionalProperties:
            type: integer
            format: int32
      additionalProperties: false
    BaselineDtoIEnumerableServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/BaselineDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ObjectServiceResponse:
      type: object
      properties:
        data: {}
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
